### ISSUE TITLE
Comply with scikit-learn convention

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/polire#1]
Let's use the sklearn convention: https://scikit-learn.org/stable/developers/contributing.html#coding-guidelines

Specifically, the API of scikit-learn objects should be very closely followed.

It might be best to just use this repository: https://github.com/scikit-learn-contrib/project-template/

**Comment by apoorvagnihotri** [comment]
Dear Prof. @nipunbatra 
Could you enable GitHub pages for the package? I was thinking to test the documentations created by sphinx.

**Comment by nipunbatra** [comment]
Please create a docs folder and I will enable pages on /docs
