### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by apoorvagnihotri** [sustainability-lab/polire#12]
@sdeepaknarayanan We need to finalize a name for the package. Some points recommended while naming the package:
- The name is suggested to not contain a negative sign
- should not be common, must be unique across all PyPi packages.

We would need to use the above info to be able to generate the docs.

**Comment by sdeepaknarayanan** [comment]
PySpatial

**Comment by sdeepaknarayanan** [comment]
That’d be my suggestion, though sir may have something else in his mind too. @nipunbatra sir, any thoughts?

**Comment by nipunbatra** [comment]
https://pyspatial.readthedocs.io/en/latest/
Can not use pyspatial

**Comment by nipunbatra** [comment]
Interpolation has Latin origin. Comes from Inter (between) and Polire (smoothen or polish). I would suggest using a name "Polire" 

The focus of this package is only on interpolation and thus let's not name it something as general as Spatial.

**Comment by nipunbatra** [comment]
I have made changes to the repo:

1. changed the name of repo
2. Added a docs folder
3. changed the name of the high level folder in the repo to Polire
4. Pushed index.html in docs folder and enabled Github pages on it: https://sustainability-lab.github.io/polire/

**Comment by apoorvagnihotri** [comment]
@nipunbatra Sir could you enable GitHub pages in `docs/_build/html`? This is the default location for the built HTML files to be stored in sphinx.
