### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/polire#2]
We should follow the standard package structure for Python projects:

please see: https://python-packaging.readthedocs.io/en/latest/minimal.html

We should also have a separate folder called notebooks where our notebooks reside.

**Comment by nipunbatra** [comment]
Currently the package structure is not being followed. 

We should have something like:
```
interpolate
-IDW

-KNN
-Utils
...
```

**Comment by apoorvagnihotri** [comment]
We have moved to this structure, therefore, closing the issue. Please kindly reopen if there are some issues still remaining.
