### ISSUE TITLE
Exact v/s Non-exact interpolation?

### ISSUE THREAD

**Issue by sdeepaknarayanan** [sustainability-lab/polire#20]
Some interpolations are exact: the value to be interpolation at the _source_ data points (aka train data) is preserved. Some don't preserve the initial points (correct me if I am wrong). As far as I can see the following are exact : 
IDW, Kriging, Trend, Spline. @apoorvagnihotri , it will be helpful if you can mention about the other techniques that you have written code for and mention their nature

**Comment by apoorvagnihotri** [comment]
@sdeepaknarayanan 
Sure. Do we necessarily want all of our methods to be returning train values for those points that are common across test and training set?

The tradeoff I was thinking about was between additional use of memory to hold the training set vs returning exact measurement value at these locations.

Further, I am not storing the training set in any of the methods (I only let the model learn the parameters), other than `SpatialAverage`. _It depends on each of the methods whether exact values would be returned or not._

If you still require which methods will return exact values, I will update you here. But the question that needs answering before that is; Do we even require that?

**Comment by sdeepaknarayanan** [comment]
> Sure. Do we necessarily want all of our methods to be returning train values for those points that are common across test and training set?
No. We do not. Not every interpolation is _exact_. Some are, some aren't. For those that are exact, it is mandatory to return the training set. I suggest we try storing it. While I understand the memory concerns, correctness takes precedence over efficiency. 

> Further, I am not storing the training set in any of the methods (I only let the model learn the parameters), other than SpatialAverage. It depends on each of the methods whether exact values would be returned or not.
That's alright. You do not need to store the training set in any of the methods, unless they can really return the proper interpolated values. Not every method has fixed parameters. It depends on the query point too (IDW is an example). For the last comment of yours on the dependence of the methods, I'd say unless you are writing code for the interpolation fully from scratch, you can let it pass (I think any method that depends on Scikit Learn or SciPy is already correct technically). But suppose you're doing something like Kriging, you need to ensure its predictions on the train set are consistent. 
 

> If you still require which methods will return exact values, I will update you here. But the question that needs answering before that is; Do we even require that?

Yes, we do. Interpolation methods usually strongly depend on the type. They are defined to be used a certain way. IDW is an example where you must preserve estimates at the training locations.

**Comment by apoorvagnihotri** [comment]
> No. We do not. Not every interpolation is exact. Some are, some aren't. For those that are exact, it is mandatory to return the training set. I suggest we try storing it. While I understand the memory concerns, correctness takes precedence over efficiency.

I see @sdeepaknarayanan . So finally we would like to have exact values for some methods and for the others not. Though how do we find which methods need to be exact?

**Comment by sdeepaknarayanan** [comment]
@apoorvagnihotri, I think wiki pages or the papers that originally defined the methods mention the constraint. An example is this:
![image](https://user-images.githubusercontent.com/24630101/61931733-1fd19300-af9f-11e9-9b24-a64ea477f8dc.png)
This is from [here](https://en.wikipedia.org/wiki/Inverse_distance_weighting). 
I think that's where interpolation differs from prediction really.

**Comment by apoorvagnihotri** [comment]
@sdeepaknarayanan I will get back to you on this.

**Comment by apoorvagnihotri** [comment]
@sdeepaknarayanan Seems like a valid point. Spline uses scikit library so we are not bothered about its nature (assuming scikit learn returns the correct values). 
Methods that I think don't need exact values to be returned are:
- CustomInterpolator (Curve fitting instead of interpolation)
- Trend (again it's curve fitting using scipy polyfit)
- Random (it's random.)
- Spline (assuming sklearn takes care)

This leaves us with Spatial Interpolation. I am not sure about this one. I would love to know your thoughts on this, Deepak.

**Comment by sdeepaknarayanan** [comment]
I think this issue has been resolved.
