### ISSUE TITLE
Topo to raster

### ISSUE THREAD

**Issue by apoorvagnihotri** [sustainability-lab/polire#27]
@nipunbatra @sdeepaknarayanan I found [this](https://gis.stackexchange.com/questions/54834/topo-to-raster-tool-for-qgis) interesting answer stating that Topo to Raster apparently isn't available anywhere.

It would be great if you could let me know your thoughts.

**Comment by sdeepaknarayanan** [comment]
We are not working on this now. Closing it for now.
