### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/polire#4]
https://github.com/sustainability-lab/spatial-interpolation/blob/87431699d4a86d804d50c904d66c1313983ed804/IDW/scikit_comply/working.py#L59

We should ensure that the code is PEP8 compliant. Most modern IDEs allow some PEP8 plugin that autoformats on saving.

**Comment by patel-zeel** [comment]
We now use `black` by default with a pre-commit hook.
