### ISSUE TITLE
Maintain Same return type across interpolators

### ISSUE THREAD

**Issue by sdeepaknarayanan** [sustainability-lab/polire#44]
For some reason, some return 1D array others 2d.

**Comment by patel-zeel** [comment]
Fixed and added automatic tests to check this.

**Comment by sdeepaknarayanan** [comment]
Hi @patel-zeel , can you close the issue by referencing the PR that fixes it?

**Comment by patel-zeel** [comment]
Thanks, @sdeepaknarayanan. #49 fixes it.
