### ISSUE TITLE
use x[a, b] instead of x[a][b]

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/polire#7]
https://github.com/sustainability-lab/spatial-interpolation/blob/87431699d4a86d804d50c904d66c1313983ed804/IDW/scikit_comply/working.py#L118

The former is quicker.

**Comment by sdeepaknarayanan** [comment]
Check IDW

**Comment by sdeepaknarayanan** [comment]
This issue was also fixed earlier.
